config/routes.rb
Rails.application.routes.draw do
  root "tickets#index"

  namespace :api do
    namespace :v1 do
      resources :tickets, only: [:create]
    end
  end

  resources :tickets, only: [:index, :show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
# frozen_string_literal: true

class Excavator < ApplicationRecord
  belongs_to :ticket

  validates :company_name, presence: true
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  has_many :excavators, dependent: :destroy

  validates :well_known_text, presence: true
end

app/controllers/api/v1/tickets_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TicketsController < ApplicationController
      skip_before_action :verify_authenticity_token

      def create
        @ticket = Ticket.new(ticket_params)
        @ticket.excavators.build(excavator_params)

        if @ticket.save
          render json: @ticket, status: :created
        else
          render json: @ticket.errors, status: :unprocessable_entity
        end
      end

      private

      def ticket_params
        {
          request_number: params['RequestNumber'],
          sequence_number: params['SequenceNumber'],
          request_type: params['RequestType'],
          request_action: params['RequestAction'],
          response_due_date_time: params.dig('DateTimes', 'ResponseDueDateTime'),
          primary_service_area_code: params.dig('ServiceArea', 'PrimaryServiceAreaCode', 'SACode'),
          additional_service_area_codes: params.dig('ServiceArea', 'AdditionalServiceAreaCodes', 'SACode'),
          well_known_text: params.dig('ExcavationInfo', 'DigsiteInfo', 'WellKnownText')
        }
      end

      def excavator_params
        excavator_data = params['Excavator']
        {
          company_name: excavator_data&.dig('CompanyName'),
          address: [
            excavator_data&.dig('Address'),
            excavator_data&.dig('City'),
            excavator_data&.dig('State'),
            excavator_data&.dig('Zip')
          ].compact.join(', '),
          crew_on_site: excavator_data&.dig('CrewOnsite')
        }
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
    wkt_parser = ::RGeo::WKRep::WKTParser.new(nil, support_ewkt: true)
    @geometry = wkt_parser.parse(@ticket.well_known_text)
    @geojson = ::RGeo::GeoJSON.encode(@geometry)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGeospatial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Tickets</h1>

  <table class="table">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Ticket request number</th>
      <th scope="col">Ticket primary service area code</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <th scope="row"><%= ticket.id %></th>
        <td><%= ticket.request_number %></td>
        <td><%= ticket.primary_service_area_code %></td>
        <td>
          <%= link_to 'Show', ticket_path(ticket), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/show.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Ticket Details</h1>

  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Ticket request number: <%= @ticket.request_number %></h5>
      <p class="card-text">Primary service area code: <%= @ticket.primary_service_area_code %></p>
      <%= link_to 'Back to tickets', tickets_path, class: 'btn btn-primary mt-3' %>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Ticket Map:</h5>
      <div id="map" data-geojson='<%= @geojson.to_json.html_safe %>' style="height: 500px; width: 100%;"></div>
    </div>
  </div>
</div>